### ISSUE TITLE
Question: Does Elixir  work on Google App Engine and Its PHP SDK?

### ISSUE THREAD

**Issue by muratsplat** [laravel/elixir#304]
Hi,

I'm developing an app buit in L5 and mostly I used JS and CSS component via Elixir. I try to work my app on Google App Engine. And so  I have detected Elixir Cache Busting files are not loaded(404) on Google App Engine SDK Server..

**Comment by JeffreyWay** [comment]
Honestly have no idea. Sorry. :) Maybe check the Laravel/Laracasts forums.

**Comment by muratsplat** [comment]
There is nothing about Laravel and Elixir experience on GAE  when it is looking  results in google and other forums.
Thank you for feed back. When I will have detected the problem, I will write that condition of Laravel Elixir on GAE

**Comment by muratsplat** [comment]
@JeffreyWay 
Laravel Elixir works on GEA very well... 

Example app.yaml
```yml
application: yourApp
version: one
runtime: php55
api_version: 1

handlers:
 - url: /favicon\.ico
   static_files: public/favicon.ico
   upload: public/favicon\.ico

 - url: /assets/(.*\.(htm$|html$|css$|js$|png$))
   static_files: public/assets/\1
   upload: public/assets/(.*\.(htm$|html$|css$|js$|png$))
   application_readable: true
# For Elixir build assets
 - url: /build/assets/(.*\.(htm$|html$|css$|js$|png$))
   static_files: public/build/assets/\1
   upload: public/build/assets/(.*\.(htm$|html$|css$|js$|png$))
   application_readable: true

 - url: /.*
   script: public/index.php

```
