### ISSUE TITLE
Wrong compile on Ubuntu

### ISSUE THREAD

**Issue by ventaquil** [laravel/elixir#370]
I have simple **SCSS** file:

```css
    @import '../template_outgame.scss';

    div#main-container {
        div#content {
            div#inside {
                table#games-table {
                    tr {
                        th {
                            @extend .text-center;
                        }

                        td {
                            &:nth-child(3), &:nth-child(4), &:nth-child(5) {
                                @extend .text-center;
                            }

                            img {
                                @include border(1px solid #777);
                                display: block;
                                margin: auto;
                                opacity: .8;
                                width: 50px;
                            }
                            img:hover {
                                border-color: #888;
                                opacity: 1;
                            }

                            div.map-name {
                                font-size: 11px;
                                margin-top: 2px;
                                line-height: .93;
                            }

                            form {
                                input[type="submit"] {
                                    float: none;
                                    max-width: 150px;
                                    min-width: 48px;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
```

When I execute `gulp` on my laptop (Win7) it's working fine. But when I run `gulp` on my Ubuntu server this part of code

```css
    &:nth-child(3), &:nth-child(4), &:nth-child(5) {
        @extend .text-center;
    }
```

compile wrong.

Only for third child have `text-align: center;` style. Child 4 and 5 don't have this style and they are sad. `th` element above working fine too. What I do wrong?

`template_outgame.scss` file: http://pastebin.com/FhfeJbZW

`global.scss` file: http://pastebin.com/eeVsjMJg

`_bootstrap.scss` is Sass Bootstrap file
