### ISSUE TITLE
Versioning inserts wrong path if relative

### ISSUE THREAD

**Issue by Propaganistas** [laravel/elixir#414]
Hi

When versioning a css file that has relative paths (e.g. FontAwesome) to versioned files (fonts, images), paths get replaced wrongly:

`versioned font-awesome.css`:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../build//fonts/fontawesome-webfont-32400f4e08.eot?v=4.5.0');
  src: url('../build//fonts/fontawesome-webfont-32400f4e08.eot?#iefix&v=4.5.0') format('embedded-opentype'), url('../build//fonts/fontawesome-webfont-db812d8a70.woff2?v=4.5.0') format('woff2'), url('../build//fonts/fontawesome-webfont-a35720c2fe.woff?v=4.5.0') format('woff'), url('../build//fonts/fontawesome-webfont-a3de2170e4.ttf?v=4.5.0') format('truetype'), url('../build//fonts/fontawesome-webfont-f775f9cca8.svg?v=4.5.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
In this example `build//`is actually superfluous, since the relative path already implies being in the build directory.
